rate = 1000

[[restrictions]]
ruleName = "cpu_usage"
threshold = 80
action = "decrease"
amount = 20

[[restrictions]]
ruleName = "mem_usage"
threshold = 80
action = "decrease"
amount = 10

[[restrictions]]
ruleName = "request_latency"
threshold = 200
action = "decrease"
amount = 15

[grayRecover]
grayScale = 0.1
recoverTime = 60