[[restrictions]]
scope = "cpu_usage"
min_threshold = 200
base_threshold = 1000
action = "decrease"
amount = 20

[[restrictions]]
scope = "mem_usage"
min_threshold = 200
base_threshold = 1000
action = "decrease"
amount = 10

[[restrictions]]
scope = "request_latency"
min_threshold = 200
base_threshold = 1000
action = "decrease"
amount = 15

[grayRecover]
grayScale = 0.1
recoverTime = 60